# Generated by Django 6.0.3 on 2026-03-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
        migrations.DeleteModel(
            name='KitchenOrder',
        ),
        migrations.DeleteModel(
            name='RestaurantOrder',
        ),
    ]
